# Generated by Django 3.2.8 on 2021-11-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_username', models.CharField(max_length=20)),
                ('post_name', models.CharField(max_length=60)),
                ('post_content', models.TextField()),
                ('post_comments', models.TextField()),
            ],
        ),
    ]
